// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJS3SFkt3H8b7k7fkK-YRSI4QiKEbcUsQ',
    appId: '1:395011186772:web:f94f52365811a5b3b44dc1',
    messagingSenderId: '395011186772',
    projectId: 'solespresspy-medicare',
    authDomain: 'solespresspy-medicare.firebaseapp.com',
    storageBucket: 'solespresspy-medicare.firebasestorage.app',
    measurementId: 'G-0WEC67B99T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdC899_KCNJ3MlwxIi99kGz3sgxS1JStM',
    appId: '1:395011186772:android:50d8f005bb60fe1bb44dc1',
    messagingSenderId: '395011186772',
    projectId: 'solespresspy-medicare',
    storageBucket: 'solespresspy-medicare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_uy79Ge7C_Luej2jSxNptQWEZuLQ-JvA',
    appId: '1:395011186772:ios:faf6bb27968c2f0fb44dc1',
    messagingSenderId: '395011186772',
    projectId: 'solespresspy-medicare',
    storageBucket: 'solespresspy-medicare.firebasestorage.app',
    androidClientId: '395011186772-s3utr991phsid7bpnpikf787jho9n8pp.apps.googleusercontent.com',
    iosClientId: '395011186772-1fsu3qe06tecroipplm7lsbv5q3la8d9.apps.googleusercontent.com',
    iosBundleId: 'com.solexpresspy.medicare',
  );

}